# colocar herbivoro ser caçado quando for comer

In [38]:
#verificar causa da moerte

import pandas as pd 
import plotly.express as px
import random 
random.seed(45)


def aplicar_mutacao(bicho):
    mutacao_tamanho = random.gauss(mu=0, sigma=0.1)
    bicho_tamanho = bicho['tamanho']
    novo_tamanho = bicho_tamanho + mutacao_tamanho

    if novo_tamanho > 0:
        bicho['tamanho'] = novo_tamanho
   
    return bicho

#definindo bicho
bicho = {
    "data_nascimento":0,
    "vivo":True,
    "expectativa_de_vida":10,
    "anos_de_vida":None,
    "data_morte":None,
    "dieta":None,
    'tamanho':None,
    'fome':None,
}


#definindo floresta
quantidade_bichos_inicial = 30
grama = 30 
crescimento_grama = 30
lista_grama = [{'ano':0,'quantidade_grama':grama}]
lista_bichos = []
dieta_lista = ["herbivoro","carnivoro"]

for _ in range(quantidade_bichos_inicial):
    bicho_inicial = bicho.copy()
    dieta = random.choices(dieta_lista,weights=[1,1])[0]
    if dieta == 'herbivoro':
        bicho_inicial['tamanho'] = random.gauss(mu=2, sigma=1.0)
    else: #carnivoro
        bicho_inicial['tamanho'] = random.gauss(mu=2, sigma=1.0)
    
    bicho_inicial['fome'] = bicho_inicial['tamanho']

    anos_de_vida = round(random.gauss(mu=bicho["expectativa_de_vida"], sigma=1.0))
    bicho_inicial['anos_de_vida'] = anos_de_vida
    bicho_inicial["dieta"] = dieta
    lista_bichos.append(bicho_inicial)

df_estado_inicial = pd.DataFrame(lista_bichos)
df_inicial_dieta = df_estado_inicial.groupby("dieta")["vivo"].count()

print("distribuicao inicial dieta:")
print(df_inicial_dieta)

#loop dos anos
max_anos = 1000

for ano_atual in range(1,max_anos+1):
    novos_bichos = []
    lista_bichos_vivos = [b for b in lista_bichos if b["vivo"]]
    for bicho in lista_bichos_vivos:

        idade = ano_atual - bicho["data_nascimento"]

        anos_de_vida = bicho['anos_de_vida']
        if idade >= anos_de_vida:
            bicho['vivo'] = False
            bicho['data_morte'] = ano_atual

        else:
            dieta = bicho["dieta"]
            tamanho = bicho['tamanho']
            fome = bicho['fome']
            
            if dieta == "carnivoro":

                presa = random.choice(lista_bichos_vivos)
                
                dieta_presa = presa["dieta"]

                if dieta_presa == "carnivoro":
                    continue
                else:   #presa = herbivoro
                    tamanho_presa = presa['tamanho']
                
                    if tamanho >= tamanho_presa:
                        presa["vivo"] = False
                        presa["data_morte"] = ano_atual
                        fome = fome - tamanho_presa
                    if fome <= 0:
                        bicho['fome'] = bicho['tamanho']
                        novo_bicho = bicho.copy()
                        novo_bicho["data_nascimento"] = ano_atual
                        novo_bicho = aplicar_mutacao(novo_bicho)
                        novos_bichos.append(novo_bicho)
                    else:
                        bicho['fome'] = fome

            else:  # é herbivoro   
                
                if grama > 0 :
                    grama -= 1
                    fome = fome - 1

                    if fome <= 0:
                        bicho['fome'] = bicho['tamanho']
                        novo_bicho = bicho.copy()
                        novo_bicho["data_nascimento"] = ano_atual
                        novo_bicho = aplicar_mutacao(novo_bicho)
                        novos_bichos.append(novo_bicho)       
                    else:
                        bicho['fome'] = fome


    info_grama = {'ano':ano_atual,'quantidade_grama':grama}
    lista_grama.append(info_grama)
    grama += crescimento_grama

    lista_bichos.extend(novos_bichos)

df_bichos = pd.DataFrame(lista_bichos)

df_grama = pd.DataFrame(lista_grama)

#adicionando coluna de idade 

df_bichos["idade"] = df_bichos["data_morte"] - df_bichos["data_nascimento"]
df_bichos.loc[df_bichos["idade"].isna(),"idade"] = max_anos - df_bichos.loc[df_bichos["idade"].isna(),"data_nascimento"] 

#analises 
def contagem_total_grafico(df):

    # conta quantos bichos nasceram em cada data
    contagem = (
        df
        .groupby("data_nascimento")
        .size()
        .reset_index(name="qtd_bichos")          # renomeia a coluna de contagem
        .sort_values("data_nascimento")         # garante ordenação
    )

    # soma acumulada
    contagem["total_acumulado"] = contagem["qtd_bichos"].cumsum()

    fig = px.line(
        contagem,
        x="data_nascimento",
        y="total_acumulado",
        title="contagem_de_bixos"
    )

    fig.show()



df_bichos["idade"].describe()

distribuicao inicial dieta:
dieta
carnivoro    11
herbivoro    19
Name: vivo, dtype: int64

count    29066.000000
mean         9.666999
std          3.062736
min          0.000000
25%         11.000000
50%         11.000000
75%         11.000000
max         11.000000
Name: idade, dtype: float64

In [39]:
def populacao_ano(df_bichos,df_grama,mostrar_grama=False,mostrar_tamanho=False):


    nascimento_ano = df_bichos.groupby(["data_nascimento","dieta"]).agg(nascimentos=("dieta","count"),tamanho_media=('tamanho','median')).reset_index()
    morte_ano = df_bichos.groupby(["data_morte","dieta"]).agg(mortes=("dieta","count")).reset_index()
    df_censo = pd.merge(nascimento_ano,morte_ano,how="outer",left_on=["data_nascimento","dieta"],right_on=["data_morte","dieta"])

    df_censo = df_censo.rename(columns={"data_nascimento":"ano"})
    df_censo.loc[df_censo["ano"].isna(),"ano"] = df_censo.loc[df_censo["ano"].isna(),"data_morte"] 

    df_censo.drop(columns=["data_morte"],inplace=True)

    start_year = int(df_censo['ano'].min())
    end_year = int(df_censo['ano'].max())

    all_years = range(start_year, end_year + 1)
    all_categories = df_censo['dieta'].unique()

    new_index = pd.MultiIndex.from_product(
        [all_categories, all_years], 
        names=['dieta', 'ano']
    )

    df_censo = (
        df_censo.set_index(['dieta', 'ano'])
        .reindex(new_index)
        .reset_index()
    )
    df_censo = df_censo.fillna(0,inplace=False)

    ordem_das_colunas = ["ano","dieta","nascimentos","mortes",'tamanho_media']
    df_censo = df_censo[ordem_das_colunas]
    df_censo = df_censo.sort_values(by="ano")
    df_censo["natalidade"] = df_censo["nascimentos"] - df_censo["mortes"]

    df_censo["populacao"] = df_censo.groupby(["dieta"])["natalidade"].transform("cumsum")

    filtro_populacao_fim_carnivoro = df_censo.loc[df_censo['dieta']=='carnivoro','populacao']== 0
    index_fim_carnivoro = df_censo.loc[df_censo['dieta']=='carnivoro'].index[filtro_populacao_fim_carnivoro][0] if filtro_populacao_fim_carnivoro.any() else None

    filtro_populacao_fim_herbivoro = df_censo.loc[df_censo['dieta']=='herbivoro','populacao']== 0
    index_fim_herbivoro = df_censo.loc[df_censo['dieta']=='herbivoro'].index[filtro_populacao_fim_herbivoro][0] if filtro_populacao_fim_herbivoro.any() else None

    print(index_fim_carnivoro)
    print(index_fim_herbivoro)
    if (index_fim_carnivoro is not None) and (index_fim_herbivoro is not None):
        index_fim = index_fim_herbivoro if index_fim_herbivoro > index_fim_carnivoro else index_fim_carnivoro
        index_fim = index_fim +2
        df_censo = df_censo.iloc[:index_fim]

    fig = px.line(
        df_censo,
        x="ano",
        y="populacao",
        color= "dieta",
       title="populacao"
    )


    #grafico grama 
    if mostrar_grama:
        fig.add_scatter(
            x=df_grama["ano"],
            y=df_grama["quantidade_grama"],
            mode="lines+markers",
            name="Quantidade de grama"
        )

    #grafico tamanho 
    if mostrar_tamanho:
            dados_carnivoro = df_censo.loc[df_censo['dieta']=='carnivoro',['ano','tamanho_media']]
            fig.add_scatter(
                x=dados_carnivoro["ano"],
                y=dados_carnivoro["tamanho_media"],
                mode="lines+markers",
                name="media de tamanho carnivoros"
            )

            dados_herbivoro = df_censo.loc[df_censo['dieta']=='herbivoro',['ano','tamanho_media']]
            fig.add_scatter(
                x=dados_herbivoro["ano"],
                y=dados_herbivoro["tamanho_media"],
                mode="lines+markers",
                name="media de tamanho herbivoro"
            )
    fig.show()

    return df_censo


    


populacao_ano(df_bichos,df_grama,mostrar_grama=False)

df_bichos.loc[df_bichos['data_nascimento']==80,'tamanho'].mean()

460
None

np.float64(0.8332982799683522)

In [40]:
def natalidade(df_bichos,df_grama):
    groupby_nascimento = df_bichos.groupby(['data_nascimento', 'dieta']).agg(contagem=('dieta', 'count')).reset_index()    
    ano_maximo = groupby_nascimento['data_nascimento'].max()
    df_grama = df_grama.loc[df_grama['ano']<=ano_maximo]


    fig = px.bar(
        groupby_nascimento,
       x="data_nascimento",
       y="contagem",
        color= "dieta",
       title="taxa natalidade"
    )

    fig.add_scatter(
        x=df_grama["ano"],
        y=df_grama["quantidade_grama"],
        mode="lines+markers",
        name="Quantidade de grama"
    )

    fig.show()

    return groupby_nascimento

natalidade(df_bichos,df_grama)

      data_nascimento      dieta  contagem
0                   0  carnivoro        11
1                   0  herbivoro        19
2                   1  herbivoro         2
3                   2  herbivoro         7
4                   3  carnivoro         3
...               ...        ...       ...
1275              996  herbivoro        30
1276              997  herbivoro        30
1277              998  herbivoro        30
1278              999  herbivoro        29
1279             1000  herbivoro        30

[1280 rows x 3 columns]

In [48]:
def tamanho(df_bichos,):
    groupby_nascimento = df_bichos.groupby(['data_nascimento', 'dieta']).agg(tamanho_medio=('tamanho', 'median')).reset_index()    


    fig = px.line(
        groupby_nascimento,
       x="data_nascimento",
       y="tamanho_medio",
        color= "dieta",
       title="tamanho medio"
    )

    fig.show()

    return groupby_nascimento

tamanho(df_bichos)

      data_nascimento      dieta  tamanho_medio
0                   0  carnivoro       2.357690
1                   0  herbivoro       2.133858
2                   1  herbivoro       0.719244
3                   2  herbivoro       0.993662
4                   3  carnivoro       3.005279
...               ...        ...            ...
1275              996  herbivoro       0.253791
1276              997  herbivoro       0.397154
1277              998  herbivoro       0.416170
1278              999  herbivoro       0.522155
1279             1000  herbivoro       0.449794

[1280 rows x 3 columns]

In [ ]:
df_bichos.loc[df_bichos['data_nascimento'] == 200]

In [52]:
df_bichos.loc[df_bichos['dieta'] == 'carnivoro'].tail(40)

,data_nascimento,vivo,expectativa_de_vida,anos_de_vida,data_morte,dieta,tamanho,fome,idade
7979,289,False,10,10,299.0,carnivoro,2.630940,1.104883,10.0
8009,290,False,10,10,300.0,carnivoro,3.366700,1.622366,10.0
8010,290,False,10,10,300.0,carnivoro,2.326315,0.030077,10.0
8099,293,False,10,10,303.0,carnivoro,2.976044,0.865734,10.0
8160,295,False,10,10,305.0,carnivoro,2.562882,1.466451,10.0
8161,295,False,10,10,305.0,carnivoro,2.324462,0.799784,10.0
8192,296,False,10,10,306.0,carnivoro,3.260661,1.439792,10.0
8281,299,False,10,10,309.0,carnivoro,2.933388,1.751188,10.0
8341,301,False,10,10,311.0,carnivoro,2.740911,1.731061,10.0
8342,301,False,10,10,311.0,carnivoro,2.373113,2.270893,10.0
8491,306,False,10,10,316.0,carnivoro,2.978010,1.450666,10.0
8548,308,False,10,10,318.0,carnivoro,2.650419,0.914037,10.0
8579,309,False,10,10,319.0,carnivoro,2.408901,2.408901,10.0
8639,311,False,10,10,321.0,carnivoro,2.882005,1.501582,10.0
8759,315,False,10,10,325.0,carnivoro,2.698049,0.673832,10.0
8819,317,False,10,10,327.0,carnivoro,2.858391,0.106566,10.0
8848,318,False,10,10,328.0,carnivoro,2.443050,1.069237,10.0
8909,320,False,10,10,330.0,carnivoro,2.537099,0.769387,10.0
9000,323,False,10,10,333.0,carnivoro,2.353978,0.825307,10.0
9090,326,False,10,10,336.0,carnivoro,2.396411,1.108741,10.0
9178,329,False,10,10,339.0,carnivoro,2.511313,1.038432,10.0
9239,331,False,10,10,341.0,carnivoro,2.473357,0.512800,10.0
9298,333,False,10,10,343.0,carnivoro,2.634410,1.357766,10.0
9449,338,False,10,10,348.0,carnivoro,2.640999,1.176043,10.0
9599,343,False,10,10,353.0,carnivoro,2.782782,0.584648,10.0
9747,348,False,10,10,358.0,carnivoro,2.895197,1.845487,10.0
9987,356,False,10,10,366.0,carnivoro,2.788179,2.516789,10.0
10224,364,False,10,10,374.0,carnivoro,2.788997,1.820770,10.0
10433,371,False,10,10,381.0,carnivoro,2.829284,1.451814,10.0
10613,377,False,10,10,387.0,carnivoro,2.853216,2.142997,10.0
10821,384,False,10,10,394.0,carnivoro,2.821130,2.066402,10.0
10998,390,False,10,10,400.0,carnivoro,2.750526,0.180911,10.0
11145,395,False,10,10,405.0,carnivoro,2.788487,2.788487,10.0
11411,404,False,10,10,414.0,carnivoro,2.830981,1.286340,10.0
11587,410,False,10,10,420.0,carnivoro,2.971939,2.971939,10.0
11854,419,False,10,10,429.0,carnivoro,2.844321,1.576472,10.0
12064,426,False,10,10,436.0,carnivoro,2.875395,2.155035,10.0
12271,433,False,10,10,443.0,carnivoro,3.033805,3.033805,10.0
12538,442,False,10,10,452.0,carnivoro,3.091780,3.048598,10.0
12776,450,False,10,10,460.0,carnivoro,3.048854,0.538570,10.0