# olhar a fome dos bichos a logica esta estranha

In [50]:
#verificar causa da moerte

import pandas as pd 
import plotly.express as px
import random 
from lista_pokemon import LISTA_POKEMON
random.seed(38)


def aplicar_mutacao(bicho):
    mutacao_tamanho = random.gauss(mu=0, sigma=0.1)
    bicho_tamanho = bicho['tamanho']
    novo_tamanho = bicho_tamanho + mutacao_tamanho

    if novo_tamanho > 0:
        bicho['tamanho'] = novo_tamanho
   
    bicho['fome'] = bicho['tamanho']

    return bicho

#definindo bicho
bicho = {
    "data_nascimento":0,
    "vivo":True,
    "expectativa_de_vida":10,
    "anos_de_vida":None,
    "data_morte":None,
    "dieta":None,
    'tamanho':None,
    'fome':None,
    'causa_morte':None,
    'geracao':0,
    'individuo':None,
    'reproducao':0
}


#definindo floresta
quantidade_bichos_inicial = 12
grama = 40
crescimento_grama = 10
lista_grama = [{'ano':0,'quantidade_grama':grama}]
lista_bichos = []
dieta_lista = ["herbivoro","carnivoro"]
lista_nomes =  LISTA_POKEMON.copy()


for _ in range(quantidade_bichos_inicial):
    bicho_inicial = bicho.copy()
    dieta = random.choices(dieta_lista,weights=[2,1])[0]
    if dieta == 'herbivoro':
        bicho_inicial['tamanho'] = random.gauss(mu=2, sigma=1.0)
    else: #carnivoro
        bicho_inicial['tamanho'] = random.gauss(mu=2, sigma=1.0)
    
    bicho_inicial['fome'] = bicho_inicial['tamanho']

    anos_de_vida = round(random.gauss(mu=bicho["expectativa_de_vida"], sigma=1.0))
    bicho_inicial['anos_de_vida'] = anos_de_vida
    bicho_inicial["dieta"] = dieta
    nome = random.choice(lista_nomes)
    lista_nomes.remove(nome)
    bicho_inicial['individuo'] = nome
    lista_bichos.append(bicho_inicial)

df_estado_inicial = pd.DataFrame(lista_bichos)
df_inicial_dieta = df_estado_inicial.groupby("dieta")["vivo"].count()

print("distribuicao inicial dieta:")
print(df_inicial_dieta)

#loop dos anos
max_anos = 1000

for ano_atual in range(1,max_anos+1):
    novos_bichos = []
    lista_bichos_vivos = [b for b in lista_bichos if b["vivo"]]
    for bicho in lista_bichos_vivos:

        idade = ano_atual - bicho["data_nascimento"]

        anos_de_vida = bicho['anos_de_vida']
        if idade >= anos_de_vida:
            bicho['vivo'] = False
            bicho['data_morte'] = ano_atual
            bicho['causa_morte'] =  'natural'

        else:
            dieta = bicho["dieta"]
            tamanho = bicho['tamanho']
            fome = bicho['fome']
            
            if dieta == "carnivoro":
                presa = random.choice(lista_bichos_vivos)
                
                dieta_presa = presa["dieta"]
                max_caca = 10

                while dieta_presa == 'herbivoro':
                    max_caca -= 1 

                    tamanho_presa = presa['tamanho']
                    sorte = random.randint(0,100)

                    if (tamanho >= tamanho_presa) and (sorte <= 30):
                        presa["vivo"] = False
                        presa["data_morte"] = ano_atual
                        presa['causa_morte'] = 'predaçao'
                        fome = fome - tamanho_presa
                        bicho['fome'] = fome
                        if fome <= 0:
                            bicho['fome'] = bicho['tamanho']
                            bicho['reproducao'] += 1 
                            novo_bicho = bicho.copy()
                            novo_bicho['reproducao'] = 0
                            novo_bicho['geracao'] += 1
                            novo_bicho["data_nascimento"] = ano_atual
                            novo_bicho = aplicar_mutacao(novo_bicho)
                            novos_bichos.append(novo_bicho)

                    presa = random.choice(lista_bichos_vivos)
                    dieta_presa = presa["dieta"]
                    if max_caca <= 0:
                        break 
                        

            else:  # é herbivoro   

                if grama >= tamanho:
                    grama -= tamanho

                    reproducao = 2
                    while reproducao > 0:
                        reproducao -= 1
                        bicho['reproducao'] += 1 
                        novo_bicho = bicho.copy()
                        novo_bicho['reproducao'] = 0
                        novo_bicho['geracao'] += 1
                        novo_bicho["data_nascimento"] = ano_atual
                        novo_bicho = aplicar_mutacao(novo_bicho)
                        novos_bichos.append(novo_bicho)       

    info_grama = {'ano':ano_atual,'quantidade_grama':grama}
    lista_grama.append(info_grama)
    grama += crescimento_grama

    lista_bichos.extend(novos_bichos)

df_bichos = pd.DataFrame(lista_bichos)

df_grama = pd.DataFrame(lista_grama)

#adicionando coluna de idade 

df_bichos["idade"] = df_bichos["data_morte"] - df_bichos["data_nascimento"]
df_bichos.loc[df_bichos["idade"].isna(),"idade"] = max_anos - df_bichos.loc[df_bichos["idade"].isna(),"data_nascimento"] 

#analises 
def contagem_total_grafico(df):

    # conta quantos bichos nasceram em cada data
    contagem = (
        df
        .groupby("data_nascimento")
        .size()
        .reset_index(name="qtd_bichos")          # renomeia a coluna de contagem
        .sort_values("data_nascimento")         # garante ordenação
    )

    # soma acumulada
    contagem["total_acumulado"] = contagem["qtd_bichos"].cumsum()

    fig = px.line(
        contagem,
        x="data_nascimento",
        y="total_acumulado",
        title="contagem_de_bixos"
    )

    fig.show()



df_bichos["idade"].describe()

distribuicao inicial dieta:
dieta
carnivoro    5
herbivoro    7
Name: vivo, dtype: int64

count    230793.000000
mean          5.420836
std           3.962177
min           0.000000
25%           2.000000
50%           4.000000
75%          10.000000
max          12.000000
Name: idade, dtype: float64

In [52]:
def populacao_ano(df_bichos,df_grama,mostrar_grama=False,mostrar_tamanho=False):


    nascimento_ano = df_bichos.groupby(["data_nascimento","dieta"]).agg(nascimentos=("dieta","count"),tamanho_media=('tamanho','median')).reset_index()
    morte_ano = df_bichos.groupby(["data_morte","dieta"]).agg(mortes=("dieta","count")).reset_index()
    df_censo = pd.merge(nascimento_ano,morte_ano,how="outer",left_on=["data_nascimento","dieta"],right_on=["data_morte","dieta"])

    df_censo = df_censo.rename(columns={"data_nascimento":"ano"})
    df_censo.loc[df_censo["ano"].isna(),"ano"] = df_censo.loc[df_censo["ano"].isna(),"data_morte"] 

    df_censo.drop(columns=["data_morte"],inplace=True)

    start_year = int(df_censo['ano'].min())
    end_year = int(df_censo['ano'].max())

    all_years = range(start_year, end_year + 1)
    all_categories = df_censo['dieta'].unique()

    new_index = pd.MultiIndex.from_product(
        [all_categories, all_years], 
        names=['dieta', 'ano']
    )

    df_censo = (
        df_censo.set_index(['dieta', 'ano'])
        .reindex(new_index)
        .reset_index()
    )
    df_censo = df_censo.fillna(0,inplace=False)

    ordem_das_colunas = ["ano","dieta","nascimentos","mortes",'tamanho_media']
    df_censo = df_censo[ordem_das_colunas]
    df_censo = df_censo.sort_values(by="ano")
    df_censo["natalidade"] = df_censo["nascimentos"] - df_censo["mortes"]

    df_censo["populacao"] = df_censo.groupby(["dieta"])["natalidade"].transform("cumsum")

    filtro_populacao_fim_carnivoro = df_censo.loc[df_censo['dieta']=='carnivoro','populacao']== 0
    index_fim_carnivoro = df_censo.loc[df_censo['dieta']=='carnivoro'].index[filtro_populacao_fim_carnivoro][0] if filtro_populacao_fim_carnivoro.any() else None

    filtro_populacao_fim_herbivoro = df_censo.loc[df_censo['dieta']=='herbivoro','populacao']== 0
    index_fim_herbivoro = df_censo.loc[df_censo['dieta']=='herbivoro'].index[filtro_populacao_fim_herbivoro][0] if filtro_populacao_fim_herbivoro.any() else None

    print(index_fim_carnivoro)
    print(index_fim_herbivoro)
    if (index_fim_carnivoro is not None) and (index_fim_herbivoro is not None):
        index_fim = index_fim_herbivoro if index_fim_herbivoro > index_fim_carnivoro else index_fim_carnivoro
        index_fim = index_fim +2
        df_censo = df_censo.iloc[:index_fim]

    fig = px.line(
        df_censo,
        x="ano",
        y="populacao",
        color= "dieta",
       title="populacao"
    )


    #grafico grama 
    if mostrar_grama:
        fig.add_scatter(
            x=df_grama["ano"],
            y=df_grama["quantidade_grama"],
            mode="lines+markers",
            name="Quantidade de grama"
        )

    #grafico tamanho 
    if mostrar_tamanho:
            dados_carnivoro = df_censo.loc[df_censo['dieta']=='carnivoro',['ano','tamanho_media']]
            fig.add_scatter(
                x=dados_carnivoro["ano"],
                y=dados_carnivoro["tamanho_media"],
                mode="lines+markers",
                name="media de tamanho carnivoros"
            )

            dados_herbivoro = df_censo.loc[df_censo['dieta']=='herbivoro',['ano','tamanho_media']]
            fig.add_scatter(
                x=dados_herbivoro["ano"],
                y=dados_herbivoro["tamanho_media"],
                mode="lines+markers",
                name="media de tamanho herbivoro"
            )
    fig.show()

    return df_censo


    


populacao_ano(df_bichos,df_grama,mostrar_grama=False)

df_bichos.loc[df_bichos['data_nascimento']==80,'tamanho'].mean()

None
None

np.float64(0.4081759012600877)

In [30]:
def natalidade(df_bichos,df_grama):
    groupby_nascimento = df_bichos.groupby(['data_nascimento', 'dieta']).agg(contagem=('dieta', 'count')).reset_index()    
    ano_maximo = groupby_nascimento['data_nascimento'].max()
    df_grama = df_grama.loc[df_grama['ano']<=ano_maximo]


    fig = px.bar(
        groupby_nascimento,
       x="data_nascimento",
       y="contagem",
        color= "dieta",
       title="taxa natalidade"
    )

    fig.add_scatter(
        x=df_grama["ano"],
        y=df_grama["quantidade_grama"],
        mode="lines+markers",
        name="Quantidade de grama"
    )

    fig.show()

    return groupby_nascimento

natalidade(df_bichos,df_grama)

    data_nascimento      dieta  contagem
0                 0  carnivoro         4
1                 0  herbivoro         8
2                 2  herbivoro         2
3                 3  herbivoro         2
4                 4  carnivoro         1
..              ...        ...       ...
81               69  herbivoro        18
82               70  herbivoro         6
83               71  herbivoro         6
84               72  herbivoro         4
85               73  herbivoro        12

[86 rows x 3 columns]

In [53]:
def tamanho(df_bichos,):
    groupby_nascimento = df_bichos.groupby(['data_nascimento', 'dieta']).agg(tamanho_medio=('tamanho', 'median')).reset_index()    


    fig = px.line(
        groupby_nascimento,
       x="data_nascimento",
       y="tamanho_medio",
        color= "dieta",
       title="tamanho medio"
    )

    fig.show()

    return groupby_nascimento

tamanho(df_bichos)

      data_nascimento      dieta  tamanho_medio
0                   0  carnivoro       3.071402
1                   0  herbivoro       1.709015
2                   1  herbivoro       1.844740
3                   2  herbivoro       1.800933
4                   3  carnivoro       3.176133
...               ...        ...            ...
1975              998  herbivoro       0.007867
1976              999  carnivoro       0.256285
1977              999  herbivoro       0.004215
1978             1000  carnivoro       0.197624
1979             1000  herbivoro       0.003965

[1980 rows x 3 columns]

In [32]:
df_herbivoros = df_bichos.loc[df_bichos['dieta'] == 'herbivoro']
df_morte = (
    df_herbivoros
    .groupby(['data_morte', 'causa_morte'])
    .size()
    .reset_index(name='mortes')
)

fig = px.line(
    df_morte,
    x="data_morte",
    y="mortes",
    color= "causa_morte",
    title="causa mortes"
)

fig.show()

In [ ]:
df_bichos.groupby('dieta')[['reproducao','idade']].describe()

          reproducao                                                  idade  \
               count      mean       std  min  25%  50%  75%   max    count
dieta
carnivoro     7164.0  0.999442  1.204487  0.0  0.0  1.0  2.0   6.0   7164.0
herbivoro    33970.0  0.999764  1.273026  0.0  0.0  0.0  2.0  12.0  33970.0


               mean       std  min   25%   50%   75%   max
dieta
carnivoro  9.934953  0.612551  0.0  10.0  10.0  10.0  10.0
herbivoro  7.159199  3.350378  0.0   4.0   9.0  10.0  11.0

In [54]:
df_bichos.groupby(['dieta','individuo']).size().reset_index()

        dieta   individuo       0
0   carnivoro  Bellsprout       4
1   carnivoro       Eevee       2
2   carnivoro      Horsea      12
3   carnivoro     Jolteon      20
4   carnivoro     Slowbro   20676
5   herbivoro       Gloom     261
6   herbivoro   Magnemite     359
7   herbivoro    Nidoking      41
8   herbivoro   Pidgeotto  209281
9   herbivoro     Poliwag      63
10  herbivoro     Snorlax      45
11  herbivoro   Vileplume      29

In [57]:
df_bichos.loc[df_bichos['individuo'] == 'Slowbro'].sort_values('geracao',ascending=True).head(40)

,data_nascimento,vivo,expectativa_de_vida,anos_de_vida,data_morte,dieta,tamanho,fome,causa_morte,geracao,individuo,reproducao,idade
8,0,False,10,11,11.0,carnivoro,3.469391,0.455604,natural,0,Slowbro,6,11.0
72,3,False,10,11,14.0,carnivoro,3.375391,0.252650,natural,1,Slowbro,1,11.0
73,3,False,10,11,14.0,carnivoro,3.523077,0.126239,natural,1,Slowbro,4,11.0
86,4,False,10,11,15.0,carnivoro,3.587435,3.587435,natural,1,Slowbro,4,11.0
119,6,False,10,11,17.0,carnivoro,3.521190,3.521190,natural,1,Slowbro,1,11.0
87,4,False,10,11,15.0,carnivoro,3.468153,0.522034,natural,1,Slowbro,1,11.0
88,4,False,10,11,15.0,carnivoro,3.724991,2.440968,natural,1,Slowbro,5,11.0
193,11,False,10,11,22.0,carnivoro,3.633301,1.527908,natural,2,Slowbro,0,11.0
212,12,False,10,11,23.0,carnivoro,3.590594,1.849161,natural,2,Slowbro,1,11.0
194,11,False,10,11,22.0,carnivoro,3.695491,2.255768,natural,2,Slowbro,0,11.0
93,4,False,10,11,15.0,carnivoro,3.487047,2.500656,natural,2,Slowbro,3,11.0
115,5,False,10,11,16.0,carnivoro,3.790848,3.790848,natural,2,Slowbro,1,11.0
114,5,False,10,11,16.0,carnivoro,3.522753,3.522753,natural,2,Slowbro,2,11.0
192,11,False,10,11,22.0,carnivoro,3.597874,0.519940,natural,2,Slowbro,3,11.0
225,13,False,10,11,24.0,carnivoro,3.511497,0.104130,natural,2,Slowbro,0,11.0
195,11,False,10,11,22.0,carnivoro,3.755675,0.269923,natural,2,Slowbro,0,11.0
94,4,False,10,11,15.0,carnivoro,3.492798,3.492798,natural,2,Slowbro,3,11.0
113,5,False,10,11,16.0,carnivoro,3.702206,3.702206,natural,2,Slowbro,1,11.0
152,8,False,10,11,19.0,carnivoro,3.834319,3.834319,natural,2,Slowbro,0,11.0
164,9,False,10,11,20.0,carnivoro,3.464292,0.927216,natural,2,Slowbro,0,11.0
142,7,False,10,11,18.0,carnivoro,3.817327,3.817327,natural,2,Slowbro,3,11.0
151,8,False,10,11,19.0,carnivoro,3.521636,3.521636,natural,2,Slowbro,1,11.0
141,7,False,10,11,18.0,carnivoro,3.305847,1.826039,natural,2,Slowbro,2,11.0
275,16,False,10,11,27.0,carnivoro,3.482586,1.107143,natural,3,Slowbro,0,11.0
216,12,False,10,11,23.0,carnivoro,3.387770,0.363709,natural,3,Slowbro,0,11.0
236,13,False,10,11,24.0,carnivoro,3.632868,3.632868,natural,3,Slowbro,3,11.0
260,15,False,10,11,26.0,carnivoro,3.323863,0.686107,natural,3,Slowbro,1,11.0
276,16,False,10,11,27.0,carnivoro,3.469616,2.055821,natural,3,Slowbro,1,11.0
296,18,False,10,11,29.0,carnivoro,3.624986,3.624986,natural,3,Slowbro,1,11.0
309,18,False,10,11,29.0,carnivoro,3.564891,3.564891,natural,3,Slowbro,2,11.0
246,14,False,10,11,25.0,carnivoro,3.646837,1.975315,natural,3,Slowbro,2,11.0
245,14,False,10,11,25.0,carnivoro,3.783412,3.783412,natural,3,Slowbro,1,11.0
197,11,False,10,11,22.0,carnivoro,3.422360,0.378582,natural,3,Slowbro,0,11.0
198,11,False,10,11,22.0,carnivoro,3.396746,1.092457,natural,3,Slowbro,1,11.0
196,11,False,10,11,22.0,carnivoro,3.508605,2.966471,natural,3,Slowbro,2,11.0
224,13,False,10,11,24.0,carnivoro,3.501583,3.501583,natural,3,Slowbro,1,11.0
199,11,False,10,11,22.0,carnivoro,3.531196,3.097617,natural,3,Slowbro,1,11.0
203,11,False,10,11,22.0,carnivoro,3.927013,0.902952,natural,3,Slowbro,0,11.0
217,12,False,10,11,23.0,carnivoro,3.412368,3.412368,natural,3,Slowbro,1,11.0
215,12,False,10,11,23.0,carnivoro,3.573760,3.573760,natural,3,Slowbro,1,11.0